// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQIv7fq87FbYH_GCqe-VLV7R0ZeAvJN2U',
    appId: '1:1086146205699:web:3b44fa935ee9111c511636',
    messagingSenderId: '1086146205699',
    projectId: 'wire-e8870',
    authDomain: 'wire-e8870.firebaseapp.com',
    storageBucket: 'wire-e8870.firebasestorage.app',
    measurementId: 'G-34XN49857D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKwDbDfqIre9GJ4rMcsvnmgWVDghdrJpw',
    appId: '1:1086146205699:android:5e006d7a4d79112f511636',
    messagingSenderId: '1086146205699',
    projectId: 'wire-e8870',
    storageBucket: 'wire-e8870.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmZziNnf4NaC7bja0SJizS01sigOM8oVY',
    appId: '1:1086146205699:ios:3ac1ec57e9745d45511636',
    messagingSenderId: '1086146205699',
    projectId: 'wire-e8870',
    storageBucket: 'wire-e8870.firebasestorage.app',
    iosBundleId: 'com.example.wireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmZziNnf4NaC7bja0SJizS01sigOM8oVY',
    appId: '1:1086146205699:ios:3ac1ec57e9745d45511636',
    messagingSenderId: '1086146205699',
    projectId: 'wire-e8870',
    storageBucket: 'wire-e8870.firebasestorage.app',
    iosBundleId: 'com.example.wireApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQIv7fq87FbYH_GCqe-VLV7R0ZeAvJN2U',
    appId: '1:1086146205699:web:b8e14c95d2ac337b511636',
    messagingSenderId: '1086146205699',
    projectId: 'wire-e8870',
    authDomain: 'wire-e8870.firebaseapp.com',
    storageBucket: 'wire-e8870.firebasestorage.app',
    measurementId: 'G-XDBNSP845T',
  );
}
